package org.drinkless.tdlib;

/**
 * Autogenerated TDLib API. (Simplified for TeleDrive)
 */
public final class TdApi {
    public abstract static class Object {}

    public abstract static class Function<T extends Object> extends Object {}

    public static class Error extends Object {
        public int code;
        public String message;
        public static final int CONSTRUCT_ID = -1679978726;
    }

    public static class Ok extends Object {
        public static final int CONSTRUCT_ID = -1640570301;
    }

    public abstract static class AuthorizationState extends Object {}
    public static class AuthorizationStateWaitTdlibParameters extends AuthorizationState {}
    public static class AuthorizationStateWaitPhoneNumber extends AuthorizationState {}
    public static class AuthorizationStateWaitCode extends AuthorizationState {}
    public static class AuthorizationStateReady extends AuthorizationState {}
    public static class AuthorizationStateLoggingOut extends AuthorizationState {}
    public static class AuthorizationStateClosing extends AuthorizationState {}
    public static class AuthorizationStateClosed extends AuthorizationState {}

    public static class AuthorizationStateWaitEncryptionKey extends AuthorizationState {
        public boolean isEncrypted;
    }

    public static class UpdateAuthorizationState extends Object {
        public AuthorizationState authorizationState;
    }

    public static class TdlibParameters extends Object {
        public boolean useTestDc;
        public String databaseDirectory;
        public String filesDirectory;
        public boolean useFileDatabase;
        public boolean useChatInfoDatabase;
        public boolean useMessageDatabase;
        public boolean useSecretChats;
        public int apiId;
        public String apiHash;
        public String systemLanguageCode;
        public String deviceModel;
        public String systemVersion;
        public String applicationVersion;
        public boolean enableStorageOptimizer;
        public boolean ignoreFileNames;
    }

    public static class SetTdlibParameters extends Function<Ok> {
        public TdlibParameters parameters;
        public SetTdlibParameters(TdlibParameters parameters) { this.parameters = parameters; }
    }

    public static class CheckDatabaseEncryptionKey extends Function<Ok> {
        public byte[] encryptionKey;
        public CheckDatabaseEncryptionKey(byte[] encryptionKey) { this.encryptionKey = encryptionKey; }
    }

    public static class SetAuthenticationPhoneNumber extends Function<Ok> {
        public String phoneNumber;
        public SetAuthenticationPhoneNumber(String phoneNumber) { this.phoneNumber = phoneNumber; }
    }

    public static class CheckAuthenticationCode extends Function<Ok> {
        public String code;
        public CheckAuthenticationCode(String code) { this.code = code; }
    }

    public static class LogOut extends Function<Ok> {}

    public static class User extends Object {
        public long id;
        public String firstName;
        public String lastName;
        public String username;
        public boolean isPremium;
    }

    public static class GetMe extends Function<User> {}

    public static class Chat extends Object {
        public long id;
        public String title;
    }

    public static class CreateNewSupergroupChat extends Function<Chat> {
        public String title;
        public boolean isChannel;
        public String description;
        public boolean forImport;
        public CreateNewSupergroupChat(String title, boolean isChannel, String description) {
            this.title = title;
            this.isChannel = isChannel;
            this.description = description;
        }
    }

    public static class ToggleSupergroupIsForum extends Function<Ok> {
        public long supergroupId;
        public boolean isForum;
        public ToggleSupergroupIsForum(long supergroupId, boolean isForum) {
            this.supergroupId = supergroupId;
            this.isForum = isForum;
        }
    }

    public static class CreateForumTopic extends Function<ForumTopicInfo> {
        public long chatId;
        public String name;
        public ForumTopicIcon icon;
        public CreateForumTopic(long chatId, String name) {
            this.chatId = chatId;
            this.name = name;
        }
    }

    public static class ForumTopicInfo extends Object {
        public long messageThreadId;
        public String name;
    }

    public static class ForumTopicIcon extends Object {}

    public abstract static class InputMessageContent extends Object {}
    public static class InputMessageDocument extends InputMessageContent {
        public InputFile document;
        public InputFile thumbnail;
        public FormattedText caption;
        public InputMessageDocument(InputFile document) { this.document = document; }
    }

    public abstract static class InputFile extends Object {}
    public static class InputFileLocal extends InputFile {
        public String path;
        public InputFileLocal(String path) { this.path = path; }
    }
    public static class InputFileRemote extends InputFile {
        public String id;
        public InputFileRemote(String id) { this.id = id; }
    }

    public static class FormattedText extends Object {
        public String text;
        public TextEntity[] entities;
        public FormattedText() {}
        public FormattedText(String text, TextEntity[] entities) {
            this.text = text;
            this.entities = entities;
        }
    }

    public static class TextEntity extends Object {
        public int offset;
        public int length;
        public TextEntityType type;
    }

    public abstract static class TextEntityType extends Object {}

    public static class InputMessageText extends InputMessageContent {
        public FormattedText text;
        public boolean disableWebPagePreview;
        public boolean clearDraft;
        public InputMessageText(FormattedText text, boolean disableWebPagePreview, boolean clearDraft) {
            this.text = text;
            this.disableWebPagePreview = disableWebPagePreview;
            this.clearDraft = clearDraft;
        }
    }

    public static class Message extends Object {
        public long id;
        public long chatId;
        public MessageContent content;
    }

    public abstract static class MessageContent extends Object {}
    public static class MessageDocument extends MessageContent {
        public Document document;
        public FormattedText caption;
    }

    public static class Document extends Object {
        public String fileName;
        public String mimeType;
        public File document;
    }

    public static class File extends Object {
        public int id;
        public int size;
        public int expectedSize;
        public LocalFile local;
        public RemoteFile remote;
    }

    public static class LocalFile extends Object {
        public String path;
        public boolean isDownloadingActive;
        public boolean isDownloadingCompleted;
        public int downloadedSize;
    }

    public static class RemoteFile extends Object {
        public String id;
        public String uniqueId;
        public boolean isUploadingActive;
        public boolean isUploadingCompleted;
        public int uploadedSize;
    }

    public static class MessageSendOptions extends Object {
        public boolean disableNotification;
        public boolean fromBackground;
        public boolean protectContent;
        public MessageSchedulingState schedulingState;
    }

    public abstract static class MessageSchedulingState extends Object {}
    public abstract static class MessageReplyTo extends Object {}

    public static class SendMessage extends Function<Message> {
        public long chatId;
        public long messageThreadId;
        public MessageReplyTo replyTo;
        public MessageSendOptions options;
        public ReplyMarkup replyMarkup;
        public InputMessageContent inputMessageContent;
        public SendMessage(long chatId, long messageThreadId, MessageReplyTo replyTo, MessageSendOptions options, ReplyMarkup replyMarkup, InputMessageContent content) {
            this.chatId = chatId;
            this.messageThreadId = messageThreadId;
            this.replyTo = replyTo;
            this.options = options;
            this.replyMarkup = replyMarkup;
            this.inputMessageContent = content;
        }
    }

    public abstract static class ReplyMarkup extends Object {}

    public static class DownloadFile extends Function<File> {
        public int fileId;
        public int priority;
        public int offset;
        public int limit;
        public boolean synchronous;
        public DownloadFile(int fileId, int priority, int offset, int limit, boolean synchronous) {
            this.fileId = fileId;
            this.priority = priority;
            this.offset = offset;
            this.limit = limit;
            this.synchronous = synchronous;
        }
    }

    public static class GetFile extends Function<File> {
        public int fileId;
        public GetFile(int fileId) { this.fileId = fileId; }
    }

    public static class GetRemoteFile extends Function<File> {
        public String remoteFileId;
        public GetRemoteFile(String remoteFileId) { this.remoteFileId = remoteFileId; }
    }

    public static class ReadFilePart extends Function<FilePart> {
        public int fileId;
        public int offset;
        public int count;
        public ReadFilePart(int fileId, int offset, int count) {
            this.fileId = fileId;
            this.offset = offset;
            this.count = count;
        }
    }

    public static class FilePart extends Object {
        public byte[] data;
    }

    public static class SaveFilePart extends Function<Ok> {
        public int fileId;
        public int partId;
        public byte[] data;
        public SaveFilePart(int fileId, int partId, byte[] data) {
            this.fileId = fileId;
            this.partId = partId;
            this.data = data;
        }
    }

    public static class MethodSaveBigFilePart extends Function<Ok> {
        public long fileId;
        public int partId;
        public int partsCount;
        public byte[] data;
        public MethodSaveBigFilePart(long fileId, int partId, int partsCount, byte[] data) {
            this.fileId = fileId;
            this.partId = partId;
            this.partsCount = partsCount;
            this.data = data;
        }
    }

    public static class UpdateFile extends Object {
        public File file;
    }

    public static class SearchChatMessages extends Function<Messages> {
        public long chatId;
        public String query;
        public long senderId;
        public long fromMessageId;
        public int offset;
        public int limit;
        public SearchChatMessages(long chatId, String query, int limit) {
            this.chatId = chatId;
            this.query = query;
            this.limit = limit;
        }
    }

    public static class Messages extends Object {
        public int totalCount;
        public Message[] messages;
    }

    public static class GetChats extends Function<Chats> {
        public int limit;
        public GetChats(int limit) { this.limit = limit; }
    }

    public static class Chats extends Object {
        public int totalCount;
        public long[] chatIds;
    }

    public static class GetChat extends Function<Chat> {
        public long chatId;
        public GetChat(long chatId) { this.chatId = chatId; }
    }
}
