package org.drinkless.tdlib;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

/**
 * Autogenerated TDLib API.
 */
public final class TdApi {
    private TdApi() {}

    public abstract static class Object {
        public abstract int getConstructor();
        @Override public String toString() { return "TdApi.Object"; }
    }

    public abstract static class Function<R extends Object> extends Object {}

    public static class Error extends Object {
        public int code;
        public String message;
        public Error() {}
        public Error(int code, String message) { this.code = code; this.message = message; }
        public static final int CONSTRUCT_ID = -1679978726;
        @Override public int getConstructor() { return CONSTRUCT_ID; }
    }

    public static class Ok extends Object {
        public Ok() {}
        public static final int CONSTRUCT_ID = -1640570301;
        @Override public int getConstructor() { return CONSTRUCT_ID; }
    }

    public abstract static class AuthorizationState extends Object {}
    public static class AuthorizationStateWaitTdlibParameters extends AuthorizationState {
        public static final int CONSTRUCT_ID = -1859345244;
        @Override public int getConstructor() { return CONSTRUCT_ID; }
    }
    public static class AuthorizationStateWaitEncryptionKey extends AuthorizationState {
        public boolean isEncrypted;
        public static final int CONSTRUCT_ID = -1026048126;
        @Override public int getConstructor() { return CONSTRUCT_ID; }
    }
    public static class AuthorizationStateWaitPhoneNumber extends AuthorizationState {
        public static final int CONSTRUCT_ID = 2028688466;
        @Override public int getConstructor() { return CONSTRUCT_ID; }
    }
    public static class AuthorizationStateWaitCode extends AuthorizationState {
        public static final int CONSTRUCT_ID = -1327173614;
        @Override public int getConstructor() { return CONSTRUCT_ID; }
    }
    public static class AuthorizationStateReady extends AuthorizationState {
        public static final int CONSTRUCT_ID = -1187422031;
        @Override public int getConstructor() { return CONSTRUCT_ID; }
    }
    public static class AuthorizationStateLoggingOut extends AuthorizationState {
        public static final int CONSTRUCT_ID = -1607567800;
        @Override public int getConstructor() { return CONSTRUCT_ID; }
    }
    public static class AuthorizationStateClosing extends AuthorizationState {
        public static final int CONSTRUCT_ID = 458315182;
        @Override public int getConstructor() { return CONSTRUCT_ID; }
    }
    public static class AuthorizationStateClosed extends AuthorizationState {
        public static final int CONSTRUCT_ID = -1476629983;
        @Override public int getConstructor() { return CONSTRUCT_ID; }
    }

    public static class UpdateAuthorizationState extends Object {
        public AuthorizationState authorizationState;
        public static final int CONSTRUCT_ID = -1004128526;
        @Override public int getConstructor() { return CONSTRUCT_ID; }
    }

    public static class TdlibParameters extends Object {
        public boolean useTestDc;
        public String databaseDirectory;
        public String filesDirectory;
        public boolean useFileDatabase;
        public boolean useChatInfoDatabase;
        public boolean useMessageDatabase;
        public boolean useSecretChats;
        public int apiId;
        public String apiHash;
        public String systemLanguageCode;
        public String deviceModel;
        public String systemVersion;
        public String applicationVersion;
        public boolean enableStorageOptimizer;
        public boolean ignoreFileNames;
        public static final int CONSTRUCT_ID = -1436423015;
        @Override public int getConstructor() { return CONSTRUCT_ID; }
    }

    public static class SetTdlibParameters extends Function<Ok> {
        public TdlibParameters parameters;
        public SetTdlibParameters() {}
        public SetTdlibParameters(TdlibParameters parameters) { this.parameters = parameters; }
        public static final int CONSTRUCT_ID = -775883218;
        @Override public int getConstructor() { return CONSTRUCT_ID; }
    }

    public static class CheckDatabaseEncryptionKey extends Function<Ok> {
        public byte[] encryptionKey;
        public CheckDatabaseEncryptionKey() {}
        public CheckDatabaseEncryptionKey(byte[] encryptionKey) { this.encryptionKey = encryptionKey; }
        public static final int CONSTRUCT_ID = -1177696435;
        @Override public int getConstructor() { return CONSTRUCT_ID; }
    }

    public static class PhoneNumberAuthenticationSettings extends Object {
        public boolean allowFlashCall;
        public boolean allowMissedCall;
        public boolean isCurrentPhoneNumber;
        public boolean allowSmsRetrieverApi;
        public Object firebaseAuthenticationSettings;
        public static final int CONSTRUCT_ID = -1869324545;
        @Override public int getConstructor() { return CONSTRUCT_ID; }
    }

    public static class SetAuthenticationPhoneNumber extends Function<Ok> {
        public String phoneNumber;
        public PhoneNumberAuthenticationSettings settings;
        public SetAuthenticationPhoneNumber() {}
        public SetAuthenticationPhoneNumber(String phoneNumber, PhoneNumberAuthenticationSettings settings) { this.phoneNumber = phoneNumber; this.settings = settings; }
        public static final int CONSTRUCT_ID = 143621422;
        @Override public int getConstructor() { return CONSTRUCT_ID; }
    }

    public static class CheckAuthenticationCode extends Function<Ok> {
        public String code;
        public CheckAuthenticationCode() {}
        public CheckAuthenticationCode(String code) { this.code = code; }
        public static final int CONSTRUCT_ID = -1300977606;
        @Override public int getConstructor() { return CONSTRUCT_ID; }
    }

    public static class LogOut extends Function<Ok> {
        public LogOut() {}
        public static final int CONSTRUCT_ID = -148679986;
        @Override public int getConstructor() { return CONSTRUCT_ID; }
    }

    public static class User extends Object {
        public long id;
        public String firstName;
        public String lastName;
        public String username;
        public boolean isPremium;
        public static final int CONSTRUCT_ID = -1367355051;
        @Override public int getConstructor() { return CONSTRUCT_ID; }
    }

    public static class GetMe extends Function<User> {
        public GetMe() {}
        public static final int CONSTRUCT_ID = -231362086;
        @Override public int getConstructor() { return CONSTRUCT_ID; }
    }

    public abstract static class ChatList extends Object {}
    public static class ChatListMain extends ChatList {
        public static final int CONSTRUCT_ID = 1324707050;
        @Override public int getConstructor() { return CONSTRUCT_ID; }
    }

    public static class Chat extends Object {
        public long id;
        public String title;
        public static final int CONSTRUCT_ID = -1551048604;
        @Override public int getConstructor() { return CONSTRUCT_ID; }
    }

    public static class Chats extends Object {
        public int totalCount;
        public long[] chatIds;
        public static final int CONSTRUCT_ID = 1445772393;
        @Override public int getConstructor() { return CONSTRUCT_ID; }
    }

    public static class GetChats extends Function<Chats> {
        public ChatList chatList;
        public int limit;
        public GetChats() {}
        public GetChats(ChatList chatList, int limit) { this.chatList = chatList; this.limit = limit; }
        public static final int CONSTRUCT_ID = -1931652391;
        @Override public int getConstructor() { return CONSTRUCT_ID; }
    }

    public static class GetChat extends Function<Chat> {
        public long chatId;
        public GetChat() {}
        public GetChat(long chatId) { this.chatId = chatId; }
        public static final int CONSTRUCT_ID = 1865242598;
        @Override public int getConstructor() { return CONSTRUCT_ID; }
    }

    public static class CreateNewSupergroupChat extends Function<Chat> {
        public String title;
        public boolean isForum;
        public String description;
        public CreateNewSupergroupChat() {}
        public CreateNewSupergroupChat(String title, boolean isForum, String description) { this.title = title; this.isForum = isForum; this.description = description; }
        public static final int CONSTRUCT_ID = -1030022415;
        @Override public int getConstructor() { return CONSTRUCT_ID; }
    }

    public static class ToggleSupergroupIsForum extends Function<Ok> {
        public long supergroupId;
        public boolean isForum;
        public ToggleSupergroupIsForum() {}
        public ToggleSupergroupIsForum(long supergroupId, boolean isForum) { this.supergroupId = supergroupId; this.isForum = isForum; }
        public static final int CONSTRUCT_ID = -479427021;
        @Override public int getConstructor() { return CONSTRUCT_ID; }
    }

    public static class ForumTopicInfo extends Object {
        public long messageThreadId;
        public String name;
        public static final int CONSTRUCT_ID = -1061922756;
        @Override public int getConstructor() { return CONSTRUCT_ID; }
    }

    public static class CreateForumTopic extends Function<ForumTopicInfo> {
        public long chatId;
        public String name;
        public CreateForumTopic() {}
        public CreateForumTopic(long chatId, String name) { this.chatId = chatId; this.name = name; }
        public static final int CONSTRUCT_ID = -744673620;
        @Override public int getConstructor() { return CONSTRUCT_ID; }
    }

    public static class FormattedText extends Object {
        public String text;
        public Object[] entities;
        public FormattedText() {}
        public FormattedText(String text, Object[] entities) { this.text = text; this.entities = entities; }
        public static final int CONSTRUCT_ID = -1187422031;
        @Override public int getConstructor() { return CONSTRUCT_ID; }
    }

    public abstract static class InputMessageContent extends Object {}
    public static class InputMessageText extends InputMessageContent {
        public FormattedText text;
        public boolean disableWebPagePreview;
        public boolean clearDraft;
        public InputMessageText() {}
        public InputMessageText(FormattedText text, boolean disableWebPagePreview, boolean clearDraft) { this.text = text; this.disableWebPagePreview = disableWebPagePreview; this.clearDraft = clearDraft; }
        public static final int CONSTRUCT_ID = -1516104332;
        @Override public int getConstructor() { return CONSTRUCT_ID; }
    }
    public static class InputMessageDocument extends InputMessageContent {
        public InputFile document;
        public InputMessageDocument() {}
        public InputMessageDocument(InputFile document) { this.document = document; }
        public static final int CONSTRUCT_ID = 205634567;
        @Override public int getConstructor() { return CONSTRUCT_ID; }
    }

    public abstract static class InputFile extends Object {}
    public static class InputFileLocal extends InputFile {
        public String path;
        public InputFileLocal() {}
        public InputFileLocal(String path) { this.path = path; }
        public static final int CONSTRUCT_ID = -1669438064;
        @Override public int getConstructor() { return CONSTRUCT_ID; }
    }

    public static class Message extends Object {
        public long id;
        public long chatId;
        public MessageContent content;
        public static final int CONSTRUCT_ID = -410713337;
        @Override public int getConstructor() { return CONSTRUCT_ID; }
    }

    public abstract static class MessageContent extends Object {}
    public static class MessageDocument extends MessageContent {
        public Document document;
        public static final int CONSTRUCT_ID = 455431671;
        @Override public int getConstructor() { return CONSTRUCT_ID; }
    }

    public static class Document extends Object {
        public String fileName;
        public String mimeType;
        public File document;
        public static final int CONSTRUCT_ID = -1067123451;
        @Override public int getConstructor() { return CONSTRUCT_ID; }
    }

    public static class File extends Object {
        public int id;
        public int size;
        public LocalFile local;
        public RemoteFile remote;
        public static final int CONSTRUCT_ID = 1803730596;
        @Override public int getConstructor() { return CONSTRUCT_ID; }
    }

    public static class LocalFile extends Object {
        public String path;
        public int downloadedSize;
        public static final int CONSTRUCT_ID = 101010101;
        @Override public int getConstructor() { return CONSTRUCT_ID; }
    }

    public static class RemoteFile extends Object {
        public String id;
        public int uploadedSize;
        public static final int CONSTRUCT_ID = 110110110;
        @Override public int getConstructor() { return CONSTRUCT_ID; }
    }

    public abstract static class MessageReplyTo extends Object {}
    public static class MessageSendOptions extends Object {
        public static final int CONSTRUCT_ID = -1516104332;
        @Override public int getConstructor() { return CONSTRUCT_ID; }
    }
    public abstract static class ReplyMarkup extends Object {}

    public static class SendMessage extends Function<Message> {
        public long chatId;
        public long messageThreadId;
        public MessageReplyTo replyTo;
        public MessageSendOptions options;
        public ReplyMarkup replyMarkup;
        public InputMessageContent inputMessageContent;
        public SendMessage() {}
        public SendMessage(long chatId, long messageThreadId, MessageReplyTo replyTo, MessageSendOptions options, ReplyMarkup replyMarkup, InputMessageContent content) {
            this.chatId = chatId; this.messageThreadId = messageThreadId; this.replyTo = replyTo; this.options = options; this.replyMarkup = replyMarkup; this.inputMessageContent = content;
        }
        public static final int CONSTRUCT_ID = -1061922756;
        @Override public int getConstructor() { return CONSTRUCT_ID; }
    }

    public static class DownloadFile extends Function<File> {
        public int fileId;
        public int priority;
        public int offset;
        public int limit;
        public boolean synchronous;
        public DownloadFile() {}
        public DownloadFile(int fileId, int priority, int offset, int limit, boolean synchronous) {
            this.fileId = fileId; this.priority = priority; this.offset = offset; this.limit = limit; this.synchronous = synchronous;
        }
        public static final int CONSTRUCT_ID = -750513904;
        @Override public int getConstructor() { return CONSTRUCT_ID; }
    }

    public static class GetRemoteFile extends Function<File> {
        public String remoteFileId;
        public GetRemoteFile() {}
        public GetRemoteFile(String remoteFileId) { this.remoteFileId = remoteFileId; }
        public static final int CONSTRUCT_ID = -1341175653;
        @Override public int getConstructor() { return CONSTRUCT_ID; }
    }

    public static class UpdateFile extends Object {
        public File file;
        public static final int CONSTRUCT_ID = 161616161;
        @Override public int getConstructor() { return CONSTRUCT_ID; }
    }

    public static class GetOption extends Function<Object> {
        public String name;
        public GetOption() {}
        public GetOption(String name) { this.name = name; }
        public static final int CONSTRUCT_ID = -1014128526;
        @Override public int getConstructor() { return CONSTRUCT_ID; }
    }
}
